// BANDS

GET http://localhost:3003/ping
###

GET http://localhost:3003/bands
###

POST http://localhost:3003/bands
Content-Type: application/json

{
    "id": "b002",
    "name": "Taxi lunar"
}
###

PUT http://localhost:3003/bands/b002
Content-Type: application/json

{
    "newName": "Kelly Key"
}
###

// SONGS

GET http://localhost:3003/songs
###

POST http://localhost:3003/songs
Content-Type: application/json

{
    "id": "m003",
    "name": "Shiny Happy People",
    "band_id": "b001"
}
###

PUT http://localhost:3003/songs/m003
Content-Type: application/json

{
    "newName": "Losing my religion"
}
###